first
ifox777/go-first-floor-sprint-five pull request #1
Opened 2024-10-20 21:21 UTC by ifox777

2024-10-21 21:44 UTC, dirtymew requested changes
Алексей

хорошая работа - но есть замечания

нужно поправить

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	meanSpeed := t.distance() / float64(t.Duration.Hours())
тут возможно деление на 0 - стоило избежать и вернуть 0 для этого случая

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	meanSpeed := t.distance() / float64(t.Duration.Hours())
также лишнее приведение типов

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	meanSpeed := t.distance() / float64(t.Duration.Hours())
и переменная тоже не нужна особо

return t.distance() / t.Duration.Hours()

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	return InfoMessage{
тут неверно - см задание

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	return InfoMessage{
тут таже ошибка

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	calories := ((CaloriesWeightMultiplier*w.Weight +
лишнее приведение типов

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	calories := ((CaloriesWeightMultiplier*w.Weight +
и тут тоже возможно деление на 0

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	meanSpeed := s.LengthPool * s.CountPool / MInKm / int(s.Duration.Hours())
тут лучше int- к float привести а не наоборот

2024-10-21 21:44 UTC, dirtymew commented on main.go
> +	return InfoMessage{
тут все ок по заданию

2024-10-22 05:14 UTC, ifox777 commented on main.go
> +	meanSpeed := s.LengthPool * s.CountPool / MInKm / int(s.Duration.Hours())
Исправлено

2024-10-22 05:14 UTC, ifox777 commented on main.go
> +	calories := ((CaloriesWeightMultiplier*w.Weight +
Исправлено

2024-10-22 05:14 UTC, ifox777 commented on main.go
> +	return InfoMessage{
Прочитал задание не понимаю, что не так. Все по описанию сделано и ответ верный

2024-10-22 05:14 UTC, ifox777 commented on main.go
> +	return InfoMessage{
Прочитал задание не понимаю, что не так. Все по описанию сделано и ответ верный

2024-10-22 05:14 UTC, ifox777 commented on main.go
> +	meanSpeed := t.distance() / float64(t.Duration.Hours())
Исправлено

2024-10-22 05:14 UTC, ifox777 commented on main.go
> +	return InfoMessage{
Ок

2024-10-22 22:12 UTC, dirtymew requested changes
Алексей

дал комментарий

вроде в задании все понятно описано

2024-10-22 22:12 UTC, dirtymew commented on main.go
> +	return InfoMessage{
<img width="805" alt="image" src="https://github.com/user-attachments/assets/13246f1b-d61a-428e-97ff-7067af41e610">

ответ верный да - но сделано не верно - тут это важно так как это касается темы спринта

2024-10-22 22:12 UTC, dirtymew commented on main.go
> +	return InfoMessage{
см ответ выше

2024-10-23 05:48 UTC, ifox777 commented on main.go
> +	return InfoMessage{
Исправлено

2024-10-23 05:48 UTC, ifox777 commented on main.go
> +	return InfoMessage{
Исправлено

2024-10-23 09:21 UTC, dirtymew approved these changes
Алексей

все отлично

зачет

2025-01-16 10:46 UTC, merged